# Generated by Django 2.2.6 on 2019-10-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
